name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkgname: [proton-native]
    steps:
      - uses: actions/checkout@v2
      - name: Clone test repo
        run: git clone https://aur.archlinux.org/${{ matrix.pkgname }}.git
      - name: Build package
        uses: ./
        id: build-package
        with:
          path: ${{ matrix.pkgname }}
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.pkgname }}-package-${{ github.run_id }}
          path: ${{ steps.build-package.outputs.pkgfile }}
